name: Kevin Luker Photography
favicon: null
layout_spectrum: 0.99915
typography_spectrum: 0.5909227402880788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#402b26'
    - '#74869c'
    - '#d88f8b'
    - '#a4adbc'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
